# Generated by Django 4.1.7 on 2023-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': ' Incidences'},
        ),
    ]
