# Generated by Django 4.1.7 on 2023-02-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportt', '0003_alter_incidences_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=models.CharField(max_length=4326),
        ),
    ]
