# Generated by Django 4.1.7 on 2023-02-17 16:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportt', '0005_alter_incidences_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, max_length=4326, null=True, srid=4326),
        ),
    ]
