# Generated by Django 4.1.7 on 2023-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportt', '0006_alter_incidences_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=models.CharField(blank=True, max_length=4326, null=True),
        ),
    ]
